name: fast_reorder
description: Library for efficient items reordering in a DB or another storages.
version: 1.0.0

environment:
  sdk: '>=2.14.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
